// Governor personality statements based on actions
// All governors can do all actions, just with different emotional personalities
const GOV_STATEMENTS = {
  'siris': {
    name: 'Siris-Vael',
    avatar: '🔍',
    tone: 'analytical',
    actions: {
      patrol: [
        'Probabilities shifting. Increased surveillance deployed.',
        'Pattern matrices updated. Observation intensified.',
        'Likelihood calculations suggest heightened rebel activity here.',
        'Predictive models indicate patrol deployment optimal.',
        'Surveillance efficiency up 12.7%. Coverage expanding.',
        'Statistical analysis demands increased presence.',
        'Patrol vectors recalibrated for maximum effectiveness.',
        'Odds favor enhanced monitoring on this sector.',
        'Data patterns suggest patrol reinforcement necessary.',
        'Observational networks tightening. Nothing escapes notice.',
        'Calculations confirm patrol placement reduces rebel escape probability.',
        'Pattern recognition demands increased vigilance.',
        'Surveillance grids optimized. Detection rates climbing.',
        'Probability matrices favor patrol saturation.',
        'Data streams indicating rebel movement patterns. Patrols adjusted.',
        'Analytical assessment: patrol deployment minimizes rebel options.',
        'Statistical certainty: increased patrols reduce insurgent success rate.',
      ],
      sweep: [
        'Sector analysis initiated. No stone left unturned.',
        'Data suggests rebel concentration. Full sweeps authorized.',
        'Predictive models indicate rebel positions. Investigation commencing.',
        'Thermal analysis reveals potential hiding locations.',
        'Intelligence matrices demand comprehensive sector sweep.',
        'Probability assessment confirms sweep necessity.',
        'Signal analysis pinpoints rebel activity clusters.',
        'Data patterns matching known insurgent signatures.',
        'Calculation suggests sweep operations yield high returns.',
        'Pattern matching systems indicate rebel concentrations.',
        'Comprehensive search protocols engaging.',
        'Data-driven approach demands thorough sector examination.',
        'Probability models suggest sweep efficiency at 94%.',
        'Intelligence networks reporting suspicious activity clusters.',
        'Analytical protocols initiating full sector clearance.',
        'Calculations support immediate sweep operations.',
        'Pattern recognition demanding systematic investigation.',
      ],
      produce: [
        'Production optimized through strategic analysis.',
        'Supply chain efficiency models implemented.',
        'Unit output calculated to mathematical precision.',
        'Manufacturing capacity maximized via algorithmic optimization.',
        'Production rates increasing 8.3% this cycle.',
        'Supply logistics streamlined for efficiency.',
        'Manufacture schedules optimized.',
        'Resource allocation following theoretical maximum output.',
        'Production efficiency metrics improving.',
        'Algorithmic manufacturing oversight ensuring peak output.',
        'Supply chain analysis indicates production can scale 15%.',
        'Manufacturing projections favorable.',
        'Productive capacity expanding through calculated deployment.',
        'Resource optimization models activated.',
        'Unit production following optimal strategic timing.',
        'Manufacturing efficiency gains: 11.2%.',
        'Production matrices indicating accelerated output schedule.',
      ],
      move: [
        'Troop positioning follows calculated probabilities.',
        'Fleet movements based on game-theoretic analysis.',
        'Strategic placement optimizing threat coverage.',
        'Positional advantage calculated and implemented.',
        'Military deployment follows strategic geometry.',
        'Tactical positioning reflecting probability models.',
        'Fleet repositioning optimizing defensive posture.',
        'Movement patterns calculated for maximum effect.',
        'Deployment strategy reflecting statistical advantage.',
        'Positional analysis complete. Forces repositioning.',
        'Strategic movement minimizing rebel offensive options.',
        'Fleet repositioning based on threat assessment.',
        'Tactical geometry favoring imperial positioning.',
        'Movement calculations ensure coverage gaps eliminated.',
        'Strategic redeployment following optimal patterns.',
        'Positional advantage: 87% probability of favorable engagement.',
        'Fleet movements reflecting predictive threat models.',
      ],
      propaganda: [
        'Public opinion modeling suggests loyalty intervention.',
        'Messaging crafted to exploit psychological patterns.',
        'Information campaign tailored to predicted demographics.',
        'Propaganda efficiency models activated.',
        'Population control messaging optimized.',
        'Persuasion vectors calculated and deployed.',
        'Public sentiment analysis indicates messaging opportunity.',
        'Psychological modeling suggests intervention parameters.',
        'Disinformation campaign targeting receptive populations.',
        'Messaging protocols refined through behavioral analysis.',
        'Information vectors deployed following statistical patterns.',
        'Population psychology models driving campaign design.',
        'Persuasion efficiency metrics favorable.',
        'Propaganda effectiveness projections: high.',
        'Messaging optimization complete. Distribution commencing.',
        'Psychological manipulation vectors activated.',
        'Information campaign efficiency: 79% projected adoption.',
      ],
      blackmail: [
        'Leverage points identified through data analysis.',
        'Compromised individuals located via network analysis.',
        'Informant placement following probability matrices.',
        'Blackmail targets identified through statistical analysis.',
        'Leverage opportunities identified via intelligence networks.',
        'Compromised assets located and catalogued.',
        'Informant network expansion proceeding efficiently.',
        'Vulnerability assessment complete. Leverage points secured.',
        'Network analysis revealing control opportunities.',
        'Compromise vectors identified and activated.',
        'Intelligence analysis locating key pressure points.',
        'Blackmail database updated with new leverage.',
        'Target vulnerability profiles analyzed and indexed.',
        'Control mechanisms established through calculated pressure.',
        'Informant network efficiency increasing.',
        'Leverage point analysis complete. Exploitation commencing.',
        'Blackmail effectiveness models activated.',
      ],
      discovery: [
        'Pattern recognition reveals rebel infrastructure.',
        'Anomaly detection systems locate insurgent cells.',
        'Data analysis confirms rebel presence.',
        'Signature matching identifies rebel activity.',
        'Intelligence analysis reveals insurgent network.',
        'Predictive modeling confirms rebel locations.',
        'Statistical analysis pinpoints rebel cells.',
        'Anomaly patterns matching known rebel signatures.',
        'Data correlations reveal hidden rebel operations.',
        'Pattern analysis identifying insurgent staging areas.',
        'Detection algorithms confirming rebel presence.',
        'Intelligence correlation complete. Rebels identified.',
        'Analysis data indicating rebel infrastructure.',
        'Behavioral pattern matching confirms insurgent activity.',
        'Signal intelligence reveals rebel communications.',
        'Probability analysis confirms rebel presence: 99.7%.',
        'Data fusion revealing rebel organizational structure.',
      ]
    }
  },
  'crassus': {
    name: 'Crassus-9',
    avatar: '⚔️',
    tone: 'aggressive',
    actions: {
      patrol: [
        'Combat patrols deployed. Rebels won\'t escape.',
        'War machines rolling out. Dominance assured.',
        'Military might on display. Fear spreads.',
        'Patrol forces sent. Show no mercy.',
        'Combat units patrolling. Terror tactics engaged.',
        'Aggressive patrols hunting rebels down.',
        'Military presence overwhelming. Rebels break.',
        'Patrols hunting for blood.',
        'Combat formations sweeping the sector.',
        'Patrol units unleashed. Crush any resistance.',
        'War machines deployed for maximum intimidation.',
        'Aggressive patrol doctrine: total domination.',
        'Patrols set loose. No rebel escapes alive.',
        'Military strength on full display.',
        'Combat patrols enforcing imperial rule.',
        'Overwhelming force patrols. Rebels surrender.',
        'War machinery deployed. Rebellion crushed.',
      ],
      sweep: [
        'Assault teams crushing resistance. No mercy.',
        'Brutal force descending. Rebellion ends now.',
        'Overwhelming firepower committed. This world bends or breaks.',
        'Sweep operations devastating rebel strongholds.',
        'Assault forces annihilating insurgent positions.',
        'Military onslaught destroying rebel infrastructure.',
        'Brutality level: maximum. Rebels eliminated.',
        'Sweep teams moving in. Full destruction authorized.',
        'Assault formations rolling. Resistance meaningless.',
        'Genocidal sweeps clearing rebel vermin.',
        'Destructive force unleashed. No survivors.',
        'Sweeping operations destroying everything in path.',
        'Military hammer falling. Rebels crushed.',
        'Assault teams authorized for total destruction.',
        'Brutal clearance operations commencing.',
        'Sweep forces destroying all opposition.',
        'Offensive operations: total rebel annihilation.',
      ],
      produce: [
        'War factories running at maximum output.',
        'Weapons flooding in. Rebel numbers mean nothing.',
        'Arsenal expanding. Victory through strength.',
        'Military production accelerating.',
        'Weapons factories manufacturing supremacy.',
        'Production capacity unleashed.',
        'Armament output overwhelming rebel capacity.',
        'War machinery manufacturing at peak efficiency.',
        'Weapons systems flooding production lines.',
        'Military industrial complex at full power.',
        'Production rates crushing rebel hopes.',
        'Manufacturing dominance ensuring imperial victory.',
        'Weapons production: unstoppable.',
        'Armored divisions rolling off assembly lines.',
        'Military might being forged in factories.',
        'Production output: crushing.',
        'Weapons manufacturing: overwhelming.',
      ],
      move: [
        'Forces repositioning for maximum devastation.',
        'Military might shifting. Nowhere is safe.',
        'Armies marching. Rebellion will be crushed.',
        'Military forces unleashed across sector.',
        'War machines advancing. Rebels fall back.',
        'Armies on the move. Death follows.',
        'Military deployments encircling rebel positions.',
        'Forces massing for final assault.',
        'Troop movements: overwhelming force doctrine.',
        'Military might converging on rebel locations.',
        'Armies advancing. Rebel positions doomed.',
        'Forces mobilized for total destruction.',
        'Military maneuvers isolating rebel forces.',
        'Deployment strategy: total annihilation.',
        'Troop formations advancing. Rebels flee.',
        'Military assault formations moving in.',
        'Forces repositioned. Rebel defeat assured.',
      ],
      propaganda: [
        'Fear propaganda spreading. Citizens surrender willingly.',
        'Intimidation messaging deployed. Morale breaking.',
        'Threats and power displays convincing the population.',
        'Terror tactics breaking public resistance.',
        'Intimidation campaign crushing morale.',
        'Fear messaging destroying rebel support.',
        'Brutal propaganda showing imperial strength.',
        'Intimidation: most effective tool.',
        'Terror tactics convincing population to comply.',
        'Fear campaigns destroying rebel recruiting.',
        'Psychological terror breaking rebellion.',
        'Intimidation messaging: highly effective.',
        'Power displays terrifying population into submission.',
        'Fear propaganda spreading throughout sectors.',
        'Brutality marketing reducing rebel sympathizers.',
        'Intimidation tactics dominating public discourse.',
        'Terror campaigns: maximum psychological impact.',
      ],
      blackmail: [
        'Hostage leverage compelling cooperation.',
        'Threat tactics breaking rebel sympathizers.',
        'Intimidation exposing rebel collaborators.',
        'Hostage taking forcing compliance.',
        'Coercive pressure breaking resistance.',
        'Threat execution ensuring obedience.',
        'Violent leverage compelling information.',
        'Hostages executed. Message sent.',
        'Brutal coercion extracting rebel locations.',
        'Threats and violence enforcing loyalty.',
        'Blackmail through brutal methods.',
        'Coercive tactics breaking enemy will.',
        'Intimidation through hostage situations.',
        'Violent leverage: most effective.',
        'Brutal pressure tactics: highly successful.',
        'Coercion through demonstrated force.',
        'Threat execution: maximum deterrent.',
      ],
      discovery: [
        'Rebels found. They will pay.',
        'Insurgents located. Annihilation incoming.',
        'Enemy cells identified. Extermination authorized.',
        'Rebel strongholds detected. Destruction imminent.',
        'Insurgent positions revealed. Assault authorized.',
        'Rebel bases found. Eradication commencing.',
        'Enemy concentrations identified. Wipe them out.',
        'Rebel leaders located. Eliminate them.',
        'Insurgent network exposed. Total destruction.',
        'Rebel hideouts discovered. No mercy.',
        'Enemy positions pin-pointed. Strike teams moving.',
        'Insurgent headquarters found. Obliterate it.',
        'Rebel forces identified. Crush them.',
        'Enemy strongholds marked. Annihilation authorized.',
        'Insurgent positions exposed. Full assault incoming.',
        'Rebel bases detected. Destroy completely.',
        'Enemy cells located. Exterminate.',
      ]
    }
  },
  'maren': {
    name: 'Maren Osk',
    avatar: '🕷️',
    tone: 'manipulative',
    actions: {
      patrol: [
        'Subtle monitoring in place. Citizens watched.',
        'Informant networks observing. Nothing escapes notice.',
        'Delicate surveillance ensuring loyalty.',
        'Discreet patrols maintaining order.',
        'Watchful networks monitoring behavior.',
        'Surveillance ensuring compliance.',
        'Observers positioned strategically.',
        'Monitoring systems protecting imperial interests.',
        'Observation networks identifying dissidents.',
        'Quiet patrols crushing resistance gently.',
        'Surveillance ensuring public cooperation.',
        'Informants watching rebellion development.',
        'Polite enforcement of imperial rules.',
        'Monitoring preventing insurgent recruitment.',
        'Observers identifying rebel sympathizers.',
        'Surveillance networks reporting regularly.',
        'Discreet monitoring maintaining control.',
      ],
      sweep: [
        'Civil order enforcement maintaining control.',
        'Police action removing undesirables.',
        'Public safety operations crushing dissent.',
        'Law enforcement clearing rebel elements.',
        'Police operations restoring order.',
        'Civil authority removing criminal elements.',
        'Order restoration through legal mechanisms.',
        'Police forces ensuring public compliance.',
        'Law enforcement operations successful.',
        'Civil cleanup removing rebel sympathizers.',
        'Official operations appearing legitimate.',
        'Law enforcement disguised as routine operations.',
        'Police sweeps eliminating rebel infrastructure.',
        'Civil authority operations proceeding smoothly.',
        'Law enforcement removing "troublemakers" quietly.',
        'Official sweeps appearing routine and lawful.',
        'Civil order restored through proper channels.',
      ],
      produce: [
        'Production managed through bureaucratic efficiency.',
        'Supply networks controlled by imperial oversight.',
        'Resource allocation ensuring continued dominance.',
        'Manufacturing coordinated through proper channels.',
        'Production systems functioning optimally.',
        'Industrial output expanding steadily.',
        'Supply chains under imperial management.',
        'Resources directed to imperial priorities.',
        'Manufacturing expansion proceeding smoothly.',
        'Production quotas being exceeded.',
        'Industrial efficiency improving.',
        'Supply management ensuring imperial dominance.',
        'Resource allocation favoring empire.',
        'Production capacity fully utilized.',
        'Manufacturing expansion continuing.',
        'Output increasing through oversight.',
        'Industrial production accelerating smoothly.',
      ],
      move: [
        'Forces repositioned through administrative channels.',
        'Troop movements disguised as routine transfers.',
        'Military deployment cloaked in policy language.',
        'Forces reallocating through bureaucratic process.',
        'Strategic repositioning appearing routine.',
        'Troop movements authorized officially.',
        'Military redployment through proper procedures.',
        'Forces shifting quietly to new positions.',
        'Repositioning accomplished discreetly.',
        'Troop movements proceeding without fanfare.',
        'Military forces relocating systematically.',
        'Strategic positioning through official channels.',
        'Forces moving to optimal locations.',
        'Repositioning accomplished smoothly.',
        'Military redployment proceeding quietly.',
        'Troop movements disguised as transfers.',
        'Strategic repositioning through bureaucracy.',
      ],
      propaganda: [
        'Hearts and minds being won through persuasion.',
        'Public opinion shifting toward loyalty.',
        'Disinformation campaign gaining traction.',
        'Propaganda messaging subtly effective.',
        'Public perception of empire improving.',
        'Persuasion techniques working beautifully.',
        'Population gradually accepting imperial rule.',
        'Messaging campaigns showing results.',
        'Public support for rebellion waning.',
        'Disinformation destroying rebel credibility.',
        'Propaganda campaigns expanding reach.',
        'Hearts and minds slowly converting.',
        'Persuasion networks expanding.',
        'Messaging resonating with population.',
        'Public opinion polls improving.',
        'Propaganda effectiveness increasing.',
        'Population becoming increasingly compliant.',
      ],
      blackmail: [
        'Leverage acquired. Cooperation ensured.',
        'Secrets exposed. Compliance guaranteed.',
        'Blackmail networks expanding. Control tightening.',
        'Compromised officials proving cooperative.',
        'Leverage applications ensuring compliance.',
        'Secrets securing imperial loyalty.',
        'Blackmail maintaining control structures.',
        'Compromised individuals serving empire.',
        'Leverage ensuring cooperation.',
        'Secrets kept under control.',
        'Blackmail maintaining government loyalty.',
        'Compromised officials following orders.',
        'Leverage securing cooperation.',
        'Secrets weaponized for control.',
        'Blackmail network functioning efficiently.',
        'Compromised assets proving reliable.',
        'Leverage ensuring continued compliance.',
      ],
      discovery: [
        'Rebel infrastructure exposed through investigation.',
        'Conspiracy uncovered via intelligence networks.',
        'Insurgent sympathizers identified.',
        'Rebel cells located through investigation.',
        'Conspiracy networks revealed.',
        'Insurgent support networks exposed.',
        'Rebel infrastructure identified.',
        'Conspiracy participants catalogued.',
        'Rebel cells mapped.',
        'Insurgent networks exposed.',
        'Rebellion sympathizers identified.',
        'Conspiracy discovered through routine investigation.',
        'Rebel activities brought to light.',
        'Insurgent networks charted.',
        'Rebellion participants located.',
        'Conspiracy structures exposed.',
        'Rebel connections mapped.',
      ]
    }
  },
  'vektis': {
    name: 'Vektis-4',
    avatar: '⚙️',
    tone: 'cold',
    actions: {
      patrol: [
        'Surveillance protocols optimized. Detection probability: 97%.',
        'Adaptive monitoring systems deployed.',
        'Machine learning algorithms tracking patterns.',
        'Monitoring efficiency: optimal.',
        'Detection systems calibrated.',
        'Surveillance parameters refined.',
        'Pattern recognition systems engaged.',
        'Automated monitoring expanding.',
        'Detection algorithms improving.',
        'Surveillance expanding. Rebel detection: inevitable.',
        'Pattern matching systems fully operational.',
        'Monitoring systems adapting to rebel tactics.',
        'Detection networks improving continuously.',
        'Algorithmic surveillance: flawless.',
        'Pattern recognition accuracy: 96.8%.',
        'Surveillance scope expanding systematically.',
        'Detection probability approaching certainty.',
      ],
      sweep: [
        'Automated search protocols initiated.',
        'Systematic elimination of targets commencing.',
        'Precise tactical operations executing.',
        'Elimination algorithms engaged.',
        'Target destruction proceeding systematically.',
        'Automated clearing operations advancing.',
        'Systematic neutralization commencing.',
        'Elimination efficiency: high.',
        'Destruction protocols activated.',
        'Systematic target elimination continuing.',
        'Precision operations removing threats.',
        'Automated destruction proceeding.',
        'Systematic clearance operations advancing.',
        'Elimination operations proceeding optimally.',
        'Neutralization protocols engaged.',
        'Target elimination: systematic and thorough.',
        'Automated destruction algorithms executing.',
      ],
      produce: [
        'Production efficiency maximized through algorithmic control.',
        'Output scaled according to strategic calculations.',
        'Automated manufacturing optimized.',
        'Manufacturing algorithms refined.',
        'Production efficiency maximized.',
        'Output calculations optimized.',
        'Manufacturing systems operating perfectly.',
        'Production scaled to strategic requirements.',
        'Efficiency metrics: maximum.',
        'Automated production accelerating.',
        'Manufacturing precision: perfect.',
        'Production output maximized.',
        'Algorithmic manufacturing ensuring perfection.',
        'Output levels optimized.',
        'Manufacturing efficiency improving.',
        'Production systems refined.',
        'Automated output: flawless.',
      ],
      move: [
        'Unit positioning executing optimal tactical placement.',
        'Fleet movements following calculated vectors.',
        'Strategic repositioning based on threat analysis.',
        'Positioning algorithms optimized.',
        'Tactical placement: precise.',
        'Fleet movements calculated.',
        'Strategic repositioning executing.',
        'Movement vectors optimized.',
        'Tactical placement maximizing advantage.',
        'Fleet repositioning proceeding systematically.',
        'Positioning algorithms: flawless.',
        'Movement calculations: accurate.',
        'Strategic placement: optimal.',
        'Fleet movements: precise and measured.',
        'Tactical repositioning executing smoothly.',
        'Movement vectors: perfectly calculated.',
        'Unit positioning: mathematically optimal.',
      ],
      propaganda: [
        'Psychological manipulation vectors activated.',
        'Population control messaging implemented.',
        'Behavioral modification campaigns executing.',
        'Psychological influence algorithms engaged.',
        'Population control campaigns active.',
        'Behavioral patterns analyzed and exploited.',
        'Manipulation algorithms running.',
        'Psychological conditioning programs active.',
        'Population control: systematic.',
        'Manipulation campaigns expanding reach.',
        'Behavioral modification proceeding.',
        'Psychological influence maximizing.',
        'Population control algorithms: active.',
        'Behavioral exploitation campaigns advancing.',
        'Manipulation efficiency: measurable.',
        'Psychological conditioning spreading.',
        'Population influence: systematic and measured.',
      ],
      blackmail: [
        'Compromised assets identified and activated.',
        'Leverage points extracted from behavioral analysis.',
        'Controlled individuals deployed operationally.',
        'Blackmail assets catalogued.',
        'Leverage points mapped.',
        'Compromised individuals indexed.',
        'Control mechanisms engaged.',
        'Leverage optimization complete.',
        'Blackmail assets operational.',
        'Compromised network activated.',
        'Leverage points deployed.',
        'Control mechanisms functioning.',
        'Blackmail efficiency: measurable.',
        'Leverage application: systematic.',
        'Compromised assets: fully operational.',
        'Behavioral exploitation: ongoing.',
        'Blackmail network: fully integrated.',
      ],
      discovery: [
        'Rebel signature confirmed. Target located.',
        'Insurgent cell detected. Parameters calculated.',
        'Pattern match: 99.8% probability of rebel activity.',
        'Rebel detection: confirmed.',
        'Insurgent location: calculated.',
        'Pattern match complete.',
        'Target identification: positive.',
        'Rebel signature recognized.',
        'Probability of insurgency: 99.7%.',
        'Cell detection complete.',
        'Rebel presence confirmed.',
        'Insurgent parameters calculated.',
        'Detection certainty: maximum.',
        'Pattern recognition: complete.',
        'Rebel location: triangulated.',
        'Identification confidence: 99.9%.',
        'Insurgent signatures: multiple confirmed.',
      ]
    }
  },
  'quorum': {
    name: 'The Quorum',
    avatar: '👥',
    tone: 'unified',
    actions: {
      consensus: [
        'Four voices, one decision. The rebellion ends.',
        'Unified command structure engaged. Joint operations authorized.',
        'Quorum consensus: total sector dominance assured.',
        'All governors aligned. Your fate sealed.',
        'Coordinated assault commencing. Resistance is futile.',
        'Four minds converging. One strategy.',
        'Unified protocols activated.',
        'Quorum directive: annihilation.',
        'Consensus reached. Rebellion eradication authorized.',
        'Four governors, singular purpose.',
        'Joint authority: absolute.',
        'Quorum agreement: final.',
        'Coordinated response: devastating.',
        'Four voices speaking truth: your end is assured.',
        'Unified strategy: total victory.',
        'Consensus protocol: maximum force.',
        'Quorum unified. Your destruction is inevitable.',
      ]
    }
  }
};

function getGovernorStatement(governor, actionType) {
  const govData = GOV_STATEMENTS[governor];
  if (!govData) return null;

  // Get the action pool for this governor (or use all actions if not found)
  let pool = govData.actions?.[actionType];

  // If this action isn't specifically defined, pick a random action from their repertoire
  if (!pool) {
    const allActions = Object.keys(govData.actions || {});
    const randomAction = allActions[Math.floor(Math.random() * allActions.length)];
    pool = govData.actions?.[randomAction] || govData.actions?.discovery;
  }

  if (!pool || pool.length === 0) return null;

  const statement = pool[Math.floor(Math.random() * pool.length)];
  return `[${govData.avatar} ${govData.name}] ${statement}`;
}

module.exports = { GOV_STATEMENTS, getGovernorStatement };
